
#user  nobody;
worker_processes 1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
  worker_connections 1024;
}


http {
  include mime.types;
  default_type application/octet-stream;

  types {
    application/javascript  js mjs;
    text/css                css;
    text/html               html;
  }

  sendfile on;
  # tcp_nopush     on;

  #keepalive_timeout  0;
  # keepalive_timeout 65;

  # gzip on;
  # gzip_buffers 32 16k;
  # gzip_comp_level 6;
  # gzip_min_length 1k;
  # gzip_static on;
  # gzip_types text/plain
  #   text/css
  #   application/javascript
  #   application/json
  #   application/x-javascript
  #   text/xml
  #   application/xml
  #   application/xml+rss
  #   text/javascript; #设置压缩的文件类型
  # gzip_vary on;

  server {
    listen 5667;
    server_name localhost;

    location /api/v1/ {
      proxy_pass ${BACKEND_SERVER_URL}/api/v1/;  # 后端服务地址，通过环境变量 BACKEND_SERVER_URL 配置
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_cache_bypass $http_upgrade;
    }

    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
      index index.html;
    }

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {
        root /usr/share/nginx/html;
    }
  }
}
